### ISSUE TITLE
Capture causes Logic to hang

### ISSUE THREAD

**Issue by jefffhaynes** [eugenecyyeh/Saleae-PD3.1-analyzer#1]
Adding a PD analyzer to the CC2 Manchester trace on the attached file causes Logic to hang.

[buggy.zip](https://github.com/eugenecyyeh/Saleae-PD3.1-analyzer/files/15444319/buggy.zip)

**Comment by jefffhaynes** [comment]
Here's a cleaner example.  Same behavior.

[buggy2.zip](https://github.com/eugenecyyeh/Saleae-PD3.1-analyzer/files/15457746/buggy2.zip)

**Comment by eugenecyyeh** [comment]
Please try version 0.0.5. The logic hangs after it misses detecting the preamble. It seems that your log did not follow package format.
Be aware that the Manchester analyzer should be set to send one bit per frame. The second log was set to 8 bits per frame.

**Comment by jefffhaynes** [comment]
Looks good, thanks.
